ExploreWithMe main part
angelich/java-explore-with-me pull request #2
Opened 2022-11-13 20:03 UTC by angelich

2022-12-05 09:18 UTC, EvgenyKoptubenko commented on README.md
> +* PR дополнительной функциональности https://github.com/angelich/java-explore-with-me/pull/3
когда проект большой, то было бы здорово иметь документацию как запустить проект и что он делает

2022-12-05 10:05 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainservice/category/CategoryAdminController.java
> +    CategoryDto createCategory(@Validated(Create.class) @RequestBody CategoryDto categoryDto) {
{
	"errors": [],
	"message": "could not execute statement; SQL [n/a]; constraint [uq_name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
	"reason": "Integrity constraint has been violated.",
	"status": "Conflict",
	"timestamp": "2022-12-05T10:04:21.721776Z"
}
Желательно добавить обработчик эксепшенов, чтобы клиент видел просто сообщение о том, что такой пользователь уже создан, а не видел имя constraint'a

2022-12-05 10:16 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainservice/user/UserController.java
> +    void deleteUser(@PathVariable Long userId) {
Если удалить несуществующего пользователя, то падает
Возвращается 500:
{
	"errors": [],
	"message": "No class ru.practicum.mainservice.user.model.User entity with id 1 exists!",
	"reason": "Error occurred.",
	"status": "Internal Server Error",
	"timestamp": "2022-12-05T10:15:50.650049Z"
}

2022-12-05 10:23 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainservice/event/EventServiceImpl.java
> +        var eventFullDto = toEventFullDto(updatedEvent);
Есть дублирование в коде, которое можно вынести в отдельный метод

var eventFullDto = toEventFullDto(eventRepository.save(savedEvent));

        var viewsStats = getEventsStats(savedEvent.getCreated(), now(), List.of("/events/" + savedEvent.getId()), false)
                .stream()
                .findFirst();
        var views = viewsStats.isPresent() ? viewsStats.get().getHits() : 0L;
        eventFullDto.setViews(views);

2022-12-05 10:23 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainservice/event/EventServiceImpl.java
> +        var eventFullDto = toEventFullDto(updatedEvent);
Так же в классе присутствует много разного дублирования.

2022-12-05 10:28 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainservice/event/EventServiceImpl.java
> +                () -> new NotFoundException("User not exist"));
По всему коду есть много строковых констант, которые дублируются. Лучше их вынести куда-то в отдельное место.
Строки, которые будет видеть пользователь, должны быть в одном месте, чтобы их можно было проще потом переводить. Желательно сделать так, чтобы они брались в зависимости от региона, который передан в приложение. Заходит пользователь из США - ему на английском, заходит из Китая - ему на китайском.

Это из разряда "можно лучше"

2022-12-05 10:31 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Замечания только из разряда "можно лучше". Если есть желание - поправь, нет - присылай обратно

2022-12-06 08:44 UTC, angelich commented on main-service/src/main/java/ru/practicum/mainservice/event/EventServiceImpl.java
> +        var eventFullDto = toEventFullDto(updatedEvent);
улучшил ситуацию, но по-хорошему, думаю, надо сделать рефакторинг

2022-12-06 08:48 UTC, angelich commented
> Работа сделана очень хорошо. Замечания только из разряда "можно лучше". Если есть желание - поправь, нет - присылай обратно

@EvgenyKoptubenko  Спасибо за ревью! Вроде бы всё поправил, хотя понимаю что еще есть что улучшить

2022-12-11 11:52 UTC, merged